apiVersion: apps/v1
kind: Deployment
metadata:
  name: creature-crafting-server
  namespace: godot-multiplayer
  labels:
    app: creature-crafting
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: creature-crafting
  template:
    metadata:
      labels:
        app: creature-crafting
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: creature-crafting-server
          image: ghcr.io/crankymagician/mt-creature-crafting-server:latest
          ports:
            - containerPort: 7777
              protocol: UDP
          env:
            - name: SAVE_API_URL
              value: "http://creature-crafting-api:3000/api"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "1Gi"
