apiVersion: v1
kind: Service
metadata:
  name: creature-crafting-server
  namespace: godot-multiplayer
  labels:
    app: creature-crafting
spec:
  type: NodePort
  selector:
    app: creature-crafting
  ports:
    - port: 7777
      targetPort: 7777
      protocol: UDP
      nodePort: 30777
